name: Backend Continuous Deployment

on:
  push:
    branches:
      - main  # Trigger on push to main branch
    paths:
      - 'starter/backend/**'  # Only trigger when files in backend folder change
      - '.github/workflows/backend-cd.yml'
  workflow_dispatch:  # Allows manual execution

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Cache pipenv virtualenv
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/virtualenvs
            ~/.cache/pipenv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run linting
        run: pipenv run lint

  test:
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Cache pipenv virtualenv
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/virtualenvs
            ~/.cache/pipenv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pipenv-

      - name: Install dependencies
        run: pipenv install --dev

      - name: Run tests
        run: pipenv run test

  build:
    name: Build Docker Image
    needs: [lint, test]  # Runs only if lint & test pass
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t backend-app:latest .
          docker images

      - name: Save Docker image
        run: docker save -o /tmp/backend-app.tar backend-app:latest

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: backend-app-image
          path: /tmp/backend-app.tar

  push-to-ecr:
    name: Push Docker Image to ECR
    needs: build  # Runs only if build succeeds
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: backend-app-image
          path: /tmp

      - name: Load Docker image
        run: docker load -i /tmp/backend-app.tar

      - name: Tag and push image to ECR
        run: |
          IMAGE_TAG=${GITHUB_SHA::7}
          docker tag backend-app:latest ${{ secrets.ECR_REPO_URL_BACKEND }}:${IMAGE_TAG}
          docker tag backend-app:latest ${{ secrets.ECR_REPO_URL_BACKEND }}:latest
          docker push ${{ secrets.ECR_REPO_URL_BACKEND }}:${IMAGE_TAG}
          docker push ${{ secrets.ECR_REPO_URL_BACKEND }}:latest
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

  deploy:
    name: Deploy to EKS
    needs: push-to-ecr  # Runs only if ECR push succeeds
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup kubectl with kubeconfig
        run: |
          mkdir -p $HOME/.kube  # Ensure the directory exists
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy to EKS
        run: |
          kubectl apply -f ./starter/backend/k8s/deployment.yaml --namespace=${{ vars.EKS_NAMESPACE }}
          kubectl apply -f ./starter/backend/k8s/service.yaml --namespace=${{ vars.EKS_NAMESPACE }}
          
          IMAGE_TAG=${GITHUB_SHA::7}
          kubectl set image deployment/backend backend=${{ secrets.ECR_REPO_URL_BACKEND }}:${IMAGE_TAG} -n ${{ vars.EKS_NAMESPACE }}
          
          kubectl rollout restart deployment backend -n ${{ vars.EKS_NAMESPACE }}
          kubectl rollout status deployment/backend -n ${{ vars.EKS_NAMESPACE }}

      - name: Verify Deployment
        run: |
          kubectl get pods --namespace=${{ vars.EKS_NAMESPACE }}